import type { User, Room, FeedPost, Product, AdminLog, MediaItem } from './types'

// ─── Free audio samples (public domain) ──────────────────────────────────────
const AUDIO = {
  a1: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-1.mp3',
  a2: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-2.mp3',
  a3: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-3.mp3',
  a4: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-4.mp3',
  a5: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-5.mp3',
  a6: 'https://www.soundhelix.com/examples/mp3/SoundHelix-Song-6.mp3',
}

// ─── Users ────────────────────────────────────────────────────────────────────
export const USERS: User[] = [
  {
    id: 'u1',
    name: 'אבי כהן',
    email: 'avi@flowroom.co',
    role: 'מפיק',
    bio: 'מפיק עם 8 שנות ניסיון בפופ, R&B ואלקטרוניקה. עבדתי עם אמנים מובילים ואני מחפש תמיד שיתופי פעולה מעניינים.',
    location: 'תל אביב',
    avatarColor: 'from-purple-500 to-pink-500',
    initials: 'אכ',
    genres: ['פופ', 'R&B', 'אלקטרוני'],
    trustScore: 94,
    songs: 47,
    collabs: 23,
    followers: 1240,
    rating: 4.8,
    completionRate: 96,
    isOnline: true,
    joinedAt: '2024-01-15',
    warnings: 0,
    isSuspended: false,
    isVerified: true,
    portfolio: [
      { id: 'p1', title: 'City Lights', genre: 'פופ', bpm: 124, key: 'Am', plays: 2400, duration: '3:42', audioUrl: AUDIO.a1, createdAt: '2024-11-01' },
      { id: 'p2', title: 'Midnight Run', genre: 'R&B', bpm: 98, key: 'F#m', plays: 1800, duration: '4:10', audioUrl: AUDIO.a2, createdAt: '2024-10-15' },
      { id: 'p3', title: 'Golden Hour', genre: 'אינדי', bpm: 108, key: 'G', plays: 956, duration: '3:55', audioUrl: AUDIO.a3, createdAt: '2024-09-20' },
    ],
    media: [
      { id: 'm1', type: 'video', url: '', thumbnail: 'https://picsum.photos/seed/u1v1/600/400', title: 'סשן הקלטה בסטודיו', caption: 'ביום של ביטים חדשים 🎹', likes: 234, views: 1820, createdAt: '2024-11-05' },
      { id: 'm2', type: 'image', url: 'https://picsum.photos/seed/u1i1/600/600', thumbnail: 'https://picsum.photos/seed/u1i1/400/400', title: 'הסטודיו שלי', caption: 'כשהמוניטורים פועלים והרעיונות זורמים', likes: 187, views: 940, createdAt: '2024-10-28' },
      { id: 'm3', type: 'reel', url: '', thumbnail: 'https://picsum.photos/seed/u1r1/400/700', title: 'טיפ: ציטוט אוטומציה ב-Logic', caption: 'טריק שחסך לי שעות', likes: 512, views: 4300, createdAt: '2024-10-15' },
      { id: 'm4', type: 'image', url: 'https://picsum.photos/seed/u1i2/600/600', thumbnail: 'https://picsum.photos/seed/u1i2/400/400', title: 'הגדרת מיקס', caption: 'Chain שעבד מצוין לסינגל האחרון', likes: 143, views: 720, createdAt: '2024-09-30' },
      { id: 'm5', type: 'video', url: '', thumbnail: 'https://picsum.photos/seed/u1v2/600/400', title: 'Behind the beat — City Lights', caption: 'מאחורי הקלעים של השיר שהתפוצץ', likes: 398, views: 2900, createdAt: '2024-09-10' },
      { id: 'm6', type: 'image', url: 'https://picsum.photos/seed/u1i3/600/600', thumbnail: 'https://picsum.photos/seed/u1i3/400/400', title: 'לייב בתל אביב', caption: 'קהל אגדי בלב העיר', likes: 290, views: 1100, createdAt: '2024-08-20' },
    ],
  },
  {
    id: 'u2',
    name: 'רון כץ',
    email: 'ron@flowroom.co',
    role: 'כותב/ת',
    bio: 'כותב טקסטים ומלחין. מתמחה בפופ ו-R&B. יש לי אלפי שורות מוכנות שרק מחכות לסאונד הנכון.',
    location: 'חיפה',
    avatarColor: 'from-blue-500 to-cyan-500',
    initials: 'רכ',
    genres: ['פופ', 'R&B', 'סול'],
    trustScore: 88,
    songs: 31,
    collabs: 17,
    followers: 780,
    rating: 4.7,
    completionRate: 91,
    isOnline: true,
    joinedAt: '2024-02-20',
    warnings: 0,
    isSuspended: false,
    isVerified: true,
    portfolio: [
      { id: 'p4', title: 'Desert Wind', genre: 'אלקטרוני', bpm: 140, key: 'Cm', plays: 3100, duration: '5:20', audioUrl: AUDIO.a4, createdAt: '2024-11-10' },
    ],
    media: [
      { id: 'm7', type: 'image', url: 'https://picsum.photos/seed/u2i1/600/600', thumbnail: 'https://picsum.photos/seed/u2i1/400/400', title: 'כתיבה מול הים', caption: 'ההשראה הכי טובה', likes: 156, views: 780, createdAt: '2024-11-08' },
      { id: 'm8', type: 'reel', url: '', thumbnail: 'https://picsum.photos/seed/u2r1/400/700', title: 'איך כותבים הוק מנצח?', caption: '60 שניות שישנו לך את ה-writing game', likes: 843, views: 7200, createdAt: '2024-10-20' },
      { id: 'm9', type: 'image', url: 'https://picsum.photos/seed/u2i2/600/600', thumbnail: 'https://picsum.photos/seed/u2i2/400/400', title: 'פנקס הכתיבה', caption: 'כל שיר מתחיל כאן', likes: 210, views: 930, createdAt: '2024-09-15' },
    ],
  },
  {
    id: 'u3',
    name: 'יעל לוי',
    email: 'yael@flowroom.co',
    role: 'זמר/ת',
    bio: 'זמרת עם קול ייחודי. מתמחה בפופ, ג\'אז ו-R&B. מחפשת מפיקים עם ויז\'ן ברור.',
    location: 'ירושלים',
    avatarColor: 'from-pink-500 to-rose-500',
    initials: 'יל',
    genres: ['פופ', 'ג\'אז', 'R&B'],
    trustScore: 91,
    songs: 22,
    collabs: 14,
    followers: 2100,
    rating: 4.9,
    completionRate: 88,
    isOnline: false,
    joinedAt: '2024-03-10',
    warnings: 0,
    isSuspended: false,
    isVerified: true,
    portfolio: [
      { id: 'p5', title: 'Blue Morning', genre: 'ג\'אז', bpm: 76, key: 'Dm', plays: 4200, duration: '4:33', audioUrl: AUDIO.a5, createdAt: '2024-10-01' },
    ],
    media: [
      { id: 'm10', type: 'video', url: '', thumbnail: 'https://picsum.photos/seed/u3v1/600/400', title: 'הקלטת הסינגל החדש', caption: 'כשהקול פגש את הביט המושלם 🎤', likes: 621, views: 5400, createdAt: '2024-11-01' },
      { id: 'm11', type: 'reel', url: '', thumbnail: 'https://picsum.photos/seed/u3r1/400/700', title: 'Cover — Blue Morning', caption: 'גרסה אקוסטית ספונטנית', likes: 1240, views: 11800, createdAt: '2024-10-25' },
      { id: 'm12', type: 'image', url: 'https://picsum.photos/seed/u3i1/600/600', thumbnail: 'https://picsum.photos/seed/u3i1/400/400', title: 'בסטודיו עם אבי', caption: 'שיתוף פעולה שהתחיל מטוויטר ונגמר בהיט', likes: 445, views: 2300, createdAt: '2024-10-10' },
      { id: 'm13', type: 'image', url: 'https://picsum.photos/seed/u3i2/600/600', thumbnail: 'https://picsum.photos/seed/u3i2/400/400', title: 'לייב בירושלים', caption: 'הבית שלי על הבמה', likes: 378, views: 1900, createdAt: '2024-09-28' },
      { id: 'm14', type: 'video', url: '', thumbnail: 'https://picsum.photos/seed/u3v2/600/400', title: 'חזרה לאלבום', caption: 'שבועות של עבודה, שניה של שיא', likes: 289, views: 1650, createdAt: '2024-08-15' },
    ],
  },
  {
    id: 'u4',
    name: 'משה שפיר',
    email: 'moshe@flowroom.co',
    role: 'מיקס',
    bio: 'מהנדס מיקס ומאסטר עם 10 שנות ניסיון. עבדתי על מאות אלבומים. הסאונד שלי — נקי, עמוק ומדויק.',
    location: 'תל אביב',
    avatarColor: 'from-yellow-500 to-orange-500',
    initials: 'מש',
    genres: ['הכל'],
    trustScore: 97,
    songs: 120,
    collabs: 64,
    followers: 3400,
    rating: 5.0,
    completionRate: 99,
    isOnline: true,
    joinedAt: '2023-12-01',
    warnings: 0,
    isSuspended: false,
    isVerified: true,
    portfolio: []
  },
  {
    id: 'u5',
    name: 'דנה ברק',
    email: 'dana@flowroom.co',
    role: 'זמר/ת',
    bio: 'זמרת R&B עם אינפלואנס מ-Soul ו-Neo-Soul. חיפשתי שנים את הפלטפורמה הנכונה — מצאתי אותה.',
    location: 'תל אביב',
    avatarColor: 'from-emerald-500 to-teal-500',
    initials: 'דב',
    genres: ['R&B', 'סול', 'Neo-Soul'],
    trustScore: 86,
    songs: 19,
    collabs: 8,
    followers: 540,
    rating: 4.6,
    completionRate: 82,
    isOnline: true,
    joinedAt: '2024-05-14',
    warnings: 0,
    isSuspended: false,
    isVerified: false,
    portfolio: [
      { id: 'p6', title: 'Velvet Sky', genre: 'R&B', bpm: 88, key: 'Em', plays: 1200, duration: '3:28', audioUrl: AUDIO.a6, createdAt: '2024-11-15' },
    ]
  },
  {
    id: 'u6',
    name: 'נועם פלד',
    email: 'noam@flowroom.co',
    role: 'מפיק',
    bio: 'מפיק אלקטרוני. בונה עולמות סאונד שלמים. מתמחה ב-EDM, טראפ ופופ אלקטרוני.',
    location: 'ירושלים',
    avatarColor: 'from-violet-500 to-purple-600',
    initials: 'נפ',
    genres: ['אלקטרוני', 'EDM', 'טראפ'],
    trustScore: 79,
    songs: 38,
    collabs: 12,
    followers: 920,
    rating: 4.5,
    completionRate: 75,
    isOnline: false,
    joinedAt: '2024-04-20',
    warnings: 1,
    isSuspended: false,
    isVerified: false,
    portfolio: []
  },
  {
    id: 'u7',
    name: 'שירה כהן',
    email: 'shira@flowroom.co',
    role: 'כותב/ת',
    bio: 'כותבת-זמרת. מגיעה מהעולם של אינדי ופולק. המילים שלי מספרות סיפורים אמיתיים.',
    location: 'תל אביב',
    avatarColor: 'from-amber-500 to-yellow-500',
    initials: 'שכ',
    genres: ['אינדי', 'פולק', 'פופ'],
    trustScore: 83,
    songs: 15,
    collabs: 9,
    followers: 630,
    rating: 4.7,
    completionRate: 87,
    isOnline: true,
    joinedAt: '2024-06-01',
    warnings: 0,
    isSuspended: false,
    isVerified: false,
    portfolio: []
  },
  {
    id: 'u8',
    name: 'עומר מור',
    email: 'omer@flowroom.co',
    role: 'נגן/ת',
    bio: 'גיטריסט ומפיק. שילוב של רוק, בלוז ופיוז\'ן. גיטרה חשמלית או אקוסטית — שניהם בשבילי.',
    location: 'תל אביב',
    avatarColor: 'from-red-500 to-orange-500',
    initials: 'עמ',
    genres: ['רוק', 'בלוז', 'פיוז\'ן'],
    trustScore: 81,
    songs: 55,
    collabs: 28,
    followers: 1800,
    rating: 4.6,
    completionRate: 90,
    isOnline: false,
    joinedAt: '2024-02-10',
    warnings: 0,
    isSuspended: false,
    isVerified: true,
    portfolio: []
  },
  {
    id: 'u9',
    name: 'רחל גולן',
    email: 'rachel@flowroom.co',
    role: 'מיקס',
    bio: 'מהנדסת סאונד מובילה. מתמחה בהיפ-הופ, R&B ופופ. כל מיקס הוא יצירת אמנות.',
    location: 'אונליין',
    avatarColor: 'from-cyan-500 to-blue-500',
    initials: 'רג',
    genres: ['היפ-הופ', 'R&B', 'פופ'],
    trustScore: 95,
    songs: 210,
    collabs: 89,
    followers: 5600,
    rating: 4.9,
    completionRate: 98,
    isOnline: true,
    joinedAt: '2023-11-15',
    warnings: 0,
    isSuspended: false,
    isVerified: true,
    portfolio: []
  },
  {
    id: 'u10',
    name: 'יובל שם-טוב',
    email: 'yuval@flowroom.co',
    role: 'עורך וידאו',
    bio: 'עורך וידאו לקליפים ותוכן דיגיטלי. עבדתי עם מאות אמנים. ביצירה הנכונה — הוידאו הוא חלק מהמוזיקה.',
    location: 'תל אביב',
    avatarColor: 'from-pink-400 to-fuchsia-500',
    initials: 'יש',
    genres: ['קולנועי', 'מוזיקה ויזואלית'],
    trustScore: 77,
    songs: 0,
    collabs: 45,
    followers: 890,
    rating: 4.5,
    completionRate: 85,
    isOnline: true,
    joinedAt: '2024-07-08',
    warnings: 0,
    isSuspended: false,
    isVerified: false,
    portfolio: []
  },
  {
    id: 'u11',
    name: 'ליאת נחום',
    email: 'liat@flowroom.co',
    role: 'שיווק',
    bio: 'מנהלת שיווק דיגיטלי לאמנים. Spotify pitching, TikTok strategy, PR. אני הגשר בין המוזיקה לקהל.',
    location: 'תל אביב',
    avatarColor: 'from-lime-500 to-green-500',
    initials: 'לנ',
    genres: ['כל הסגנונות'],
    trustScore: 88,
    songs: 0,
    collabs: 38,
    followers: 1200,
    rating: 4.8,
    completionRate: 93,
    isOnline: false,
    joinedAt: '2024-03-25',
    warnings: 0,
    isSuspended: false,
    isVerified: true,
    portfolio: []
  },
  {
    id: 'u12',
    name: 'גיל אבן',
    email: 'gil@flowroom.co',
    role: 'מפיק',
    bio: 'מפיק בינוני, מחפש שיתופי פעולה חדשים. התחלתי לפני שנה ויש לי המון רצון ללמוד ולצמוח.',
    location: 'באר שבע',
    avatarColor: 'from-slate-500 to-gray-500',
    initials: 'גא',
    genres: ['פופ', 'אלקטרוני'],
    trustScore: 62,
    songs: 8,
    collabs: 3,
    followers: 120,
    rating: 4.1,
    completionRate: 65,
    isOnline: false,
    joinedAt: '2024-09-01',
    warnings: 2,
    isSuspended: false,
    isVerified: false,
    portfolio: []
  },
]

// ─── Rooms ────────────────────────────────────────────────────────────────────
export const ROOMS: Room[] = [
  {
    id: 'r1',
    name: 'City Lights EP',
    description: 'אלבום EP של 4 שירים בסגנון פופ/R&B. יש לנו את הבסיס — עכשיו מרימים את זה',
    currentStage: 3,
    genre: 'פופ / R&B',
    isActive: true,
    createdAt: '2024-11-01',
    updatedAt: '2024-12-15',
    members: [
      { userId: 'u1', role: 'מפיק', split: 35, joinedAt: '2024-11-01', hasSigned: true },
      { userId: 'u2', role: 'כותב', split: 25, joinedAt: '2024-11-02', hasSigned: true },
      { userId: 'u3', role: 'זמרת', split: 25, joinedAt: '2024-11-03', hasSigned: false },
      { userId: 'u4', role: 'מיקס', split: 15, joinedAt: '2024-11-05', hasSigned: true },
    ],
    stems: [
      { id: 's1', name: 'Drums_v3.wav', size: '42MB', uploadedBy: 'u2', uploadedAt: 'לפני שעה', audioUrl: AUDIO.a1 },
      { id: 's2', name: 'Bass_final.wav', size: '18MB', uploadedBy: 'u1', uploadedAt: 'אתמול', audioUrl: AUDIO.a2 },
      { id: 's3', name: 'Melody_draft.wav', size: '31MB', uploadedBy: 'u1', uploadedAt: 'לפני 3 ימים', audioUrl: AUDIO.a3 },
      { id: 's4', name: 'Vocals_rough.wav', size: '55MB', uploadedBy: 'u3', uploadedAt: 'השבוע', audioUrl: AUDIO.a4 },
    ],
    activity: [
      { id: 'ac1', userId: 'u2', action: 'העלה Drums_v3.wav', time: '09:42', type: 'upload' },
      { id: 'ac2', userId: 'u3', action: 'הגיבה: "הבאס יצא מעולה!"', time: '10:15', type: 'comment' },
      { id: 'ac3', userId: 'u4', action: 'עדכן את שלב ההפקה', time: '11:30', type: 'update' },
      { id: 'ac4', userId: 'u1', action: 'הוסיף הערה על המלודיה', time: '13:00', type: 'comment' },
      { id: 'ac5', userId: 'u2', action: 'ביקש חוות דעת על המיקס', time: '14:22', type: 'comment' },
    ],
    tasks: [
      { id: 't1', text: 'בניית מבנה מוזיקלי מלא', done: true, assignedTo: 'u1', stage: 3 },
      { id: 't2', text: 'ייצוא תופים לערוצים', done: true, assignedTo: 'u2', stage: 3 },
      { id: 't3', text: 'הוספת שכבות כלי מיתר', done: false, assignedTo: 'u1', stage: 3 },
      { id: 't4', text: 'עיצוב מנגינה סינתטית', done: false, assignedTo: 'u4', stage: 3 },
      { id: 't5', text: 'השוואה לשיר ייחוס', done: false, assignedTo: 'u3', stage: 3 },
    ],
    chatMessages: [
      { id: 'cm1', userId: 'u2', text: 'הי כולם! מה חושבים על הדמו האחרון?', createdAt: 'אתמול 18:30' },
      { id: 'cm2', userId: 'u3', text: 'יצא ממש טוב! הבאס חזק 🔥', createdAt: 'אתמול 18:45' },
      { id: 'cm3', userId: 'u1', text: 'נסיים את השכבות השבוע ואז נעביר למשה למיקס', createdAt: 'היום 09:00' },
    ],
  },
  {
    id: 'r2',
    name: 'Midnight Sessions',
    description: 'פרויקט אינדי-פופ. מחפשים צליל אותנטי, לא מלוטש יתר על המידה.',
    currentStage: 1,
    genre: 'אינדי פופ',
    isActive: true,
    createdAt: '2024-12-01',
    updatedAt: '2024-12-14',
    members: [
      { userId: 'u7', role: 'כותבת', split: 40, joinedAt: '2024-12-01', hasSigned: true },
      { userId: 'u5', role: 'זמרת', split: 35, joinedAt: '2024-12-02', hasSigned: true },
      { userId: 'u6', role: 'מפיק', split: 25, joinedAt: '2024-12-03', hasSigned: false },
    ],
    stems: [
      { id: 's5', name: 'Demo_v1.mp3', size: '8MB', uploadedBy: 'u7', uploadedAt: 'לפני יומיים', audioUrl: AUDIO.a5 },
    ],
    activity: [
      { id: 'ac6', userId: 'u7', action: 'יצרה את החדר', time: '2024-12-01', type: 'join' },
      { id: 'ac7', userId: 'u5', action: 'הצטרפה לחדר', time: '2024-12-02', type: 'join' },
      { id: 'ac8', userId: 'u7', action: 'העלתה Demo_v1.mp3', time: '2024-12-12', type: 'upload' },
    ],
    tasks: [
      { id: 't6', text: 'כתיבת פזמון ראשי', done: true, assignedTo: 'u7', stage: 1 },
      { id: 't7', text: 'קביעת מפתח ו-BPM', done: false, assignedTo: 'u6', stage: 1 },
      { id: 't8', text: 'הקלטת דמו ראשוני', done: false, assignedTo: 'u5', stage: 1 },
    ],
    chatMessages: [
      { id: 'cm4', userId: 'u7', text: 'מישהו יכול לבוא לסטודיו ביום שישי?', createdAt: 'לפני יומיים' },
    ],
  },
  {
    id: 'r3',
    name: 'Desert Vibes',
    description: 'פרויקט אלקטרוני עם השפעות מזרחיות. משלב עוד ומודרני.',
    currentStage: 5,
    genre: 'אלקטרוני / מזרחי',
    isActive: true,
    createdAt: '2024-09-15',
    updatedAt: '2024-12-10',
    members: [
      { userId: 'u1', role: 'מפיק', split: 30, joinedAt: '2024-09-15', hasSigned: true },
      { userId: 'u8', role: 'גיטרה', split: 30, joinedAt: '2024-09-16', hasSigned: true },
      { userId: 'u9', role: 'מיקס', split: 20, joinedAt: '2024-09-20', hasSigned: true },
      { userId: 'u3', role: 'וקאלים', split: 10, joinedAt: '2024-10-01', hasSigned: true },
      { userId: 'u11', role: 'שיווק', split: 10, joinedAt: '2024-10-05', hasSigned: true },
    ],
    stems: [
      { id: 's6', name: 'Full_Mix_v7.wav', size: '89MB', uploadedBy: 'u9', uploadedAt: 'לפני 3 ימים', audioUrl: AUDIO.a6 },
      { id: 's7', name: 'Guitar_final.wav', size: '44MB', uploadedBy: 'u8', uploadedAt: 'לפני שבוע', audioUrl: AUDIO.a1 },
    ],
    activity: [
      { id: 'ac9', userId: 'u9', action: 'העלתה Full_Mix_v7.wav', time: '3 ימים', type: 'upload' },
      { id: 'ac10', userId: 'u1', action: 'אישר את המיקס', time: '2 ימים', type: 'update' },
    ],
    tasks: [
      { id: 't9', text: 'מיקס סופי', done: true, assignedTo: 'u9', stage: 5 },
      { id: 't10', text: 'מאסטרינג', done: false, assignedTo: 'u4', stage: 5 },
      { id: 't11', text: 'כיסוי לאלבום', done: false, assignedTo: 'u10', stage: 5 },
    ],
    chatMessages: [
      { id: 'cm5', userId: 'u9', text: 'העלתי את המיקס הסופי — תשמעו ותגידו!', createdAt: 'לפני 3 ימים' },
      { id: 'cm6', userId: 'u1', text: 'שמעתי. מעולה! רק הבס קצת חזק בריף', createdAt: 'לפני יומיים' },
    ],
  },
  {
    id: 'r4',
    name: 'New Wave Project',
    description: 'ניסוי בסאונד — שיר חד פעמי. מחפשים לראות לאן הולך.',
    currentStage: 0,
    genre: 'ניסיוני',
    isActive: true,
    createdAt: '2024-12-14',
    updatedAt: '2024-12-14',
    members: [
      { userId: 'u6', role: 'מפיק', split: 50, joinedAt: '2024-12-14', hasSigned: true },
      { userId: 'u12', role: 'מפיק', split: 50, joinedAt: '2024-12-14', hasSigned: false },
    ],
    stems: [],
    activity: [
      { id: 'ac11', userId: 'u6', action: 'יצר את החדר', time: 'אתמול', type: 'join' },
    ],
    tasks: [
      { id: 't12', text: 'הגדרת כיוון מוזיקלי', done: false, assignedTo: 'u6', stage: 0 },
    ],
    chatMessages: [],
  },
]

// ─── Feed ─────────────────────────────────────────────────────────────────────
export const FEED_POSTS: FeedPost[] = [
  {
    id: 'f1',
    userId: 'u1',
    content: 'העלתי סקיצה חדשה לפרויקט City Lights 🎵 מחפש זמר/ת עם ווייב R&B לאלבום הקרוב — יש מישהו?',
    type: 'audio',
    audioUrl: AUDIO.a1,
    audioDuration: '1:23',
    likes: 47,
    comments: [
      { id: 'c1', userId: 'u3', text: 'אני!! שלח לי הודעה', createdAt: 'לפני שעה' },
      { id: 'c2', userId: 'u5', text: 'הסאונד מדהים, אני גם זמינה', createdAt: 'לפני 45 דקות' },
    ],
    createdAt: 'לפני 2 שעות',
    isLiked: false,
    collabRole: 'זמר/ת R&B',
  },
  {
    id: 'f2',
    userId: 'u3',
    content: 'סיימתי להקליט את הווקאלים הראשיים לסשנים של חצות 🎤 אחרי שלושה שבועות של עבודה — סוף סוף מרגיש אמיתי. תודה לצוות הנפלא!',
    type: 'text',
    likes: 83,
    comments: [
      { id: 'c3', userId: 'u1', text: 'שיחה לאחרונה וזה מדהים! ❤️', createdAt: 'לפני 3 שעות' },
      { id: 'c4', userId: 'u4', text: 'הקול שלך תמיד מגבה הכל', createdAt: 'לפני 2 שעות' },
    ],
    createdAt: 'לפני 5 שעות',
    isLiked: true,
  },
  {
    id: 'f3',
    userId: 'u2',
    content: 'מחפש מפיק לשיר פופ/אלקטרוני שכתבתי. יש לי מלודיה וטקסט מלא — צריך מישהו שיביא את הסאונד הנכון. בתשלום.',
    type: 'collab',
    likes: 31,
    comments: [
      { id: 'c5', userId: 'u6', text: 'שלח לי! זה בדיוק הז\'אנר שלי', createdAt: 'לפני שעה' },
    ],
    createdAt: 'אתמול',
    isLiked: false,
    collabRole: 'מפיק פופ/אלקטרוני',
  },
  {
    id: 'f4',
    userId: 'u9',
    content: 'הנה קטע מהמיקס האחרון שעשיתי. 14 שעות בסטודיו — שווה כל רגע 🎧',
    type: 'audio',
    audioUrl: AUDIO.a3,
    audioDuration: '0:45',
    likes: 124,
    comments: [
      { id: 'c6', userId: 'u8', text: 'הבאס לוגן!', createdAt: 'לפני 2 שעות' },
      { id: 'c7', userId: 'u1', text: 'מאיפה את לוקחת הילוכים כאלה?!', createdAt: 'לפני שעה' },
    ],
    createdAt: 'לפני יומיים',
    isLiked: true,
  },
  {
    id: 'f5',
    userId: 'u7',
    content: 'מחפשת מפיק/ה עם יד קלה לפרויקט אינדי-פולק. הטקסטים כתובים, יש לי מלודיה — צריכה מישהו שמבין את הז\'אנר.',
    type: 'collab',
    likes: 19,
    comments: [],
    createdAt: 'לפני 3 ימים',
    isLiked: false,
    collabRole: 'מפיק אינדי/פולק',
  },
  {
    id: 'f6',
    userId: 'u5',
    content: 'Velvet Sky יצא! 🌙 הקשיבו לשיר הראשון שלי בפלטפורמה. כל הקרדיט לצוות — אתם הכי.',
    type: 'audio',
    audioUrl: AUDIO.a6,
    audioDuration: '3:28',
    likes: 201,
    comments: [
      { id: 'c8', userId: 'u1', text: 'ממש ממש מרגש! 🔥', createdAt: 'לפני 6 שעות' },
      { id: 'c9', userId: 'u3', text: 'הקול שלך שוחט. כל הכבוד!', createdAt: 'לפני 5 שעות' },
      { id: 'c10', userId: 'u11', text: 'אני פה לקמפיין שיווקי אם תרצי!', createdAt: 'לפני 4 שעות' },
    ],
    createdAt: 'לפני 4 ימים',
    isLiked: false,
  },
]

// ─── Marketplace ──────────────────────────────────────────────────────────────
export const PRODUCTS: Product[] = [
  {
    id: 'pr1',
    title: 'חבילת ביטים — לו-פיי צ\'יל',
    sellerId: 'u1',
    price: 180,
    type: 'ביט',
    rating: 4.8,
    sales: 47,
    audioUrl: AUDIO.a1,
    description: '10 ביטים לו-פיי מוכנים לשימוש. לייסנס מסחרי מלא.',
    isPremium: false,
  },
  {
    id: 'pr2',
    title: 'סשן מיקס מקצועי',
    sellerId: 'u9',
    price: 320,
    type: 'מיקס',
    rating: 4.9,
    sales: 89,
    description: 'מיקס מקצועי לשיר אחד. עד 32 ערוצים. דלאוורי ב-72 שעות.',
    isPremium: false,
  },
  {
    id: 'pr3',
    title: 'מילים — ורס R&B',
    sellerId: 'u2',
    price: 90,
    type: 'מילים',
    rating: 4.7,
    sales: 23,
    description: 'כתיבת ורס R&B מקורי. הגשה ב-48 שעות. שינויים כלולים.',
    isPremium: false,
  },
  {
    id: 'pr4',
    title: 'מאסטרקלאס: אבלטון לייב',
    sellerId: 'u1',
    price: 250,
    type: 'קורס',
    rating: 4.9,
    sales: 134,
    description: '8 שעות וידאו. מהתחלה ועד שיר מוגמר. גישה לכל החיים.',
    isPremium: false,
  },
  {
    id: 'pr5',
    title: 'מאסטרינג לאלבום',
    sellerId: 'u4',
    price: 1200,
    type: 'מאסטר',
    rating: 5.0,
    sales: 31,
    description: 'מאסטרינג מקצועי לאלבום מלא (עד 12 שירים). Analog + Digital chain.',
    isPremium: false,
  },
  {
    id: 'pr6',
    title: 'ערכת רשתות חברתיות',
    sellerId: 'u11',
    price: 150,
    type: 'שיווק',
    rating: 4.6,
    sales: 56,
    description: 'תוכן לרשתות ל-30 יום. כולל Spotify pitch, TikTok strategy ו-press kit.',
    isPremium: false,
  },
  {
    id: 'pr7',
    title: 'ליווי מפיק בכיר — חבילה מלאה',
    sellerId: 'u1',
    price: 4800,
    type: 'פרימיום',
    rating: 5.0,
    sales: 8,
    description: '12 שבועות ליווי אישי צמוד. A&R, פידבק שבועי, גישה לרשת מקצועית ועוד.',
    isPremium: true,
  },
  {
    id: 'pr8',
    title: 'מיקס + מאסטר — חבילה משולבת',
    sellerId: 'u9',
    price: 550,
    type: 'מיקס',
    rating: 4.9,
    sales: 44,
    audioUrl: AUDIO.a3,
    description: 'מיקס ומאסטר בחבילה אחת. חיסכון של 30%. עד 48 ערוצים.',
    isPremium: false,
  },
]

// ─── Admin logs ───────────────────────────────────────────────────────────────
export const ADMIN_LOGS: AdminLog[] = [
  { id: 'al1', action: 'משתמש חדש נרשם', targetUser: 'u12', adminId: 'admin', createdAt: '2024-12-14 09:15' },
  { id: 'al2', action: 'אזהרה נשלחה', targetUser: 'u6', adminId: 'admin', createdAt: '2024-12-13 14:30' },
  { id: 'al3', action: 'אזהרה נשלחה', targetUser: 'u12', adminId: 'admin', createdAt: '2024-12-12 11:00' },
  { id: 'al4', action: 'פרופיל אומת', targetUser: 'u8', adminId: 'admin', createdAt: '2024-12-11 16:45' },
  { id: 'al5', action: 'חדר יצירה נוצר', targetUser: 'r1', adminId: 'system', createdAt: '2024-11-01 10:00' },
]

export const STAGES = [
  { id: 0, name: 'רעיון', sub: 'הגדרת הכיוון המוזיקלי' },
  { id: 1, name: 'כתיבה', sub: 'מילים, מבנה, קונספט' },
  { id: 2, name: 'הלחנה', sub: 'מלודיה, הרמוניות' },
  { id: 3, name: 'הפקה', sub: 'הפקה מלאה, עיצוב מוזיקלי' },
  { id: 4, name: 'הקלטה', sub: 'הקלטת וקאלים, נגינה' },
  { id: 5, name: 'מיקס/מאסטר', sub: 'עיבוד סאונד סופי' },
  { id: 6, name: 'שחרור', sub: 'הפצה ושיווק' },
]

export function getUserById(id: string) {
  return USERS.find(u => u.id === id)
}

export function getRoomById(id: string) {
  return ROOMS.find(r => r.id === id)
}
